import Sidebar from "./component/Sidebar"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const res = await fetch("http://localhost:9999/posts", {cache:'no-cache'});
  const team = await res.json();
// team.map((team)=>{
//   console.log(team.team)
// })
  return (
    <html>
      <body>  
        <Sidebar team={team}/>
        {children}
        </body>
    </html>
  )
}
